version: "3"

services:

    caddy:
        container_name: "lnmp_caddy"
        image: "abiosoft/caddy"
        environment:
            ACME_AGREE: "true"
        volumes:
            - "./caddy/Caddyfile:/etc/Caddyfile"
            - "./caddy/data:/root/.caddy"
            - "./logs/caddy:/logs:rw"
            - "./socks:/socks:rw"
            - "./www:/www"
        ports:
            - "80:80"
            - "443:443"

    php-fpm:
        container_name: "lnmp_php_fpm"
        image: "php:fpm-alpine"
        volumes:
            - "./php-fpm/php.ini:/usr/local/etc/php/php.ini"
            - "./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
            - "./logs/php:/logs:rw"
            - "./socks:/socks:rw"
            - "./www:/www"

    mariadb:
        container_name: "lnmp_mariadb"
        image: "mariadb"
        user: mysql
        volumes:
            - "./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf"
            - "./mariadb/data:/var/lib/mysql:rw"
            - "./logs/mariadb:/logs:rw"
            - "./socks:/socks:rw"

        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: "test_user"
            MYSQL_PASSWORD: "test_pass"
            MYSQL_DATABASE: "test_db"
