version: "3"

services:
    nginx:
        image: "nginx:alpine"
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/conf:/etc/nginx/conf"
            - "./logs/nginx:/var/log/nginx"
            - "./socks:/socks"
            - "./www:/www"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
          - php-fpm
    php-fpm:
      image: "php:fpm-alpine"
      volumes:
            - "./php-fpm/php.ini:/usr/local/etc/php/php.ini"
            - "./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
            - "./socks:/socks"
            - "./www:/www"
            - "./logs/php:/logs"

    # mariadb:
    #     image: "mariadb"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "password"
    #         MYSQL_USER: "test_user"
    #         MYSQL_PASSWORD: "test_pass"
    #         MYSQL_DATABASE: "test_db"
